/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        display: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      colors: {
        teal: {
          400: '#2DD4BF',
          500: '#14B8A6',
          600: '#0D9488',
          700: '#0F766E',
        },
        amber: {
          400: '#FBBF24',
          500: '#F59E0B',
          600: '#D97706',
        },
        danger: '#DC2626',
        success: '#059669',
        'bg-dark': '#020617',
        'bg-mid': '#0F172A',
        'bg-card': 'rgba(15, 23, 42, 0.55)',
        'bg-elevated': 'rgba(30, 41, 59, 0.50)',
        text: '#F8FAFC',
        'text-muted': '#CBD5E1',
        'text-subtle': '#94A3B8',
        'text-dim': '#64748B',
        border: '#334155',
        'border-hover': '#475569',
      },
      animation: {
        'pulse-glow': 'pulse-glow 3s ease-in-out infinite',
        'fade-up': 'fade-up 0.6s ease-out forwards',
        'float': 'float 6s ease-in-out infinite',
        'float-slow': 'float-slow 8s ease-in-out infinite',
        'float-slower': 'float-slower 10s ease-in-out infinite',
        'gradient-shift': 'gradient-shift 4s ease-in-out infinite',
        'border-glow': 'border-glow 3s ease-in-out infinite',
        'ping-slow': 'ping-slow 3s cubic-bezier(0, 0, 0.2, 1) infinite',
        'bounce-gentle': 'bounce-gentle 2s ease-in-out infinite',
      },
      keyframes: {
        'pulse-glow': { '0%, 100%': { opacity: '0.4' }, '50%': { opacity: '0.8' } },
        'fade-up': { from: { opacity: '0', transform: 'translateY(24px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'float': { '0%, 100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-20px)' } },
        'float-slow': { '0%, 100%': { transform: 'translateY(0px) scale(1)' }, '50%': { transform: 'translateY(-28px) scale(1.05)' } },
        'float-slower': { '0%, 100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-36px)' } },
        'gradient-shift': { '0%, 100%': { 'background-position': '0% 50%' }, '50%': { 'background-position': '100% 50%' } },
        'border-glow': { '0%, 100%': { 'border-color': 'rgba(45, 212, 191, 0.15)' }, '50%': { 'border-color': 'rgba(45, 212, 191, 0.45)' } },
        'ping-slow': { '75%, 100%': { transform: 'scale(2)', opacity: '0' } },
        'bounce-gentle': { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-8px)' } },
      },
    },
  },
  plugins: [],
}
